#!/usr/bin/perl
#
# Compare filebench results
#
# Usage: filebench_summary <dir1> <dir2> ...
#

use CGI ':standard';

$maxiopsoverall = 0;
$maxiopsrate = 0;
$maxbandwidth = 0;

#
# Create html and text
#
open (HTML, ">index.html");
print HTML start_html(-title=>'Filebench');
print HTML "<body>";
#
# Print aggregate flowop stats
#
foreach $dir (@ARGV) {

    print "dir = $dir\n";
    printf ("Generating html for $dir\n");
    open (PROFILE, "<$dir/thisrun.prof");
    $description = <PROFILE>;
    $description =~ s/.*"(.+)".*/$1/;

    $files = `ls $dir/stats.*.out $dir/*/stats.*.out 2>/dev/null`;
    foreach $file (split(/\n/, $files)) {
	print "file = $file\n";
	($prefix, $workload, $fstype) = split(/\./, $file);
	$dataset = $dir;
	$dataset =~ s/.*\/(.+)$/$1/;
	$dataset =~ s/\/$//;
        $desc{$dataset} = "$description";
	print "dataset = $dataset\n";
	print "workload = $workload\n";
	print "fstype = $fstype\n";
	open (STATS, $file);
	$tmp = <STATS>;
	while (<STATS>) {
	    ($flowop, $ops, $bandwidth, $latency, $cpu, $wait, $seconds) = split(/[ \t]+/, $_);
	    
	    if (/^$/) {
		$tmp = <STATS>;
	        ($fluff, $opcnt, $ops, $reads, $writes, $bandwidth, 
		    $cpu) = split(/[ \tA-z:\/,]+/, $tmp);
	        $ops{$workload, $dataset} = $ops;
	  	last;
	    }
	    
	    $ops =~ s/ops\/s//;
	    $bandwidth =~ s/mb\/s//;
	    $latency =~ s/ms\/op//;
	    $cpu =~ s/us\/op//;
	    
	    # Collapse shadow reads into single metric
	    if ($flowop =~ /shadowread/) {
		$flowop = "shadow-read";
	    }
	    
	    # Collapse database writes into single metric
	    if ($flowop =~ /db.*write/) {
		$flowop = "db-write";
	    }
	    
	    # Collapse database writes into single metric
	    if ($flowop =~ /db.*write/) {
		$flowop = "db-write";
	    }
	    
	    $datasets{$dataset} = $dataset;
	    $workloads{$workload} = $workload;

	    $flowops{$flowop} = $flowop;
	    $wkl_flowops{$flowop, $workload} = $flowop;
	    $wkl_workload{$flowop, $workload} = $workload;
	    $flow_ops{$flowop, $workload, $dataset} += $ops;
	    $flow_bandwidth{$flowop, $workload, $dataset} += $bandwidth;
	    $flow_latency{$flowop, $workload, $dataset} += $latency;
	    $flow_cpu{$flowop, $workload, $dataset} += $cpu;

	    $bandwidth{$workload, $dataset} += $bandwidth;
	    $latency{$workload, $dataset} += $latency;
	    $cpu{$workload, $dataset} += $cpu;

	    $flowopcnt{$flowop, $workload, $dataset}++;
	    $workloadcnt{$workload, $dataset}++;
	}
	close(STATS);
    }
}

# HTML IOPS
print HTML h1('Throughput breakdown (ops per second)');
print HTML "<table border=1>";
print HTML "<b><td>Workload</td>";
foreach $dataset (sort {$a cmp $b}(keys %datasets)) {
    print HTML "<td>$desc{$dataset}</td>";
}
print HTML "</b></tr>";

foreach $workload (sort (keys %workloads)) {
    print HTML "<b><tr><td>$workload</td>";
    $last = 0;
    foreach $dataset (sort {$a cmp $b}(keys %datasets)) {
	$color = "white";
        $this = $ops{$workload, $dataset};
        if ($last && ($this - $last) < ($last * -0.1)) {
		$color = "red";
        }
        if ($last && ($this - $last) > ($last * 0.1)) {
		$color = "green";
	}
        printf HTML ("<td><a href=\"$dataset/$workload/html/index.html\">%d</a></td>\n", $this);
	$last = $ops{$workload, $dataset};
    }
    print HTML "</b></tr>";
}
print HTML "</table>";

# HTML Bandwidth
print HTML h1('Bandwidth breakdown (MB/s)');
print HTML "<table border=1>";
print HTML "<td>Workload</td>";
foreach $dataset (sort {$a cmp $b}(keys %datasets)) {
    print HTML "<td>$desc{$dataset}</td>";
}
print HTML "</tr>";
foreach $workload (sort (keys %workloads)) {
    $bandwidth = 0;
    foreach $dataset (sort {$a cmp $b}(keys %datasets)) {
	$bandwidth +=  $bandwidth{$workload, $dataset};
    }
    next if ($bandwidth == 0);
    print HTML "<tr><td>$workload</td>";
    foreach $dataset (sort {$a cmp $b}(keys %datasets)) {
	printf HTML ("<td>%d</td>\n", $bandwidth{$workload, $dataset});
    }
    print HTML "</tr>";
}
print HTML "</table>";

# HTML Latency
print HTML h1('Latency breakdown (ms per op)');
print HTML "<table border=1>";
print HTML "<td>Workload</td>";
foreach $dataset (sort {$a cmp $b}(keys %datasets)) {
    print HTML "<td>$desc{$dataset}</td>";
}

print HTML "</tr>";
foreach $workload (sort (keys %workloads)) {
    print HTML "<tr><td>$workload</td>";
    foreach $dataset (sort {$a cmp $b}(keys %datasets)) {
	if ( $workloadcnt{$workload, $dataset}) {
	    printf HTML ("<td>%.1f</td>", $latency{$workload,
		$dataset} / $workloadcnt{$workload, $dataset});
        } else {
             printf HTML ("<td></td>");
        }
    }
    print HTML "</tr>";
    foreach $flowop (keys %wkl_flowops) {
        next if ("$wkl_workload{$flowop}" ne "$workload");
        print HTML "<tr><td><i>__$wkl_flowops{$flowop}</td>";
        foreach $dataset (sort {$a cmp $b}(keys %datasets)) {
	     if ( $flowopcnt{$flowop, $dataset}) {
	         printf HTML ("<td>%.1f</td>\n", $flow_latency{$flowop, 
		    $dataset} / $flowopcnt{$flowop, $dataset});
             } else {
	         printf HTML ("<td></td>");
             }
        }
        print HTML "</i></tr>";
    }
}
print HTML "</table>";

# HTML Efficiency
print HTML h1('Efficiency breakdown (Code path length in uS/op)');
print HTML "<table border=1>";
print HTML "<td>Workload</td>";
foreach $dataset (sort {$a cmp $b}(keys %datasets)) {
    print HTML "<td>$desc{$dataset}</td>";
}
print HTML "</tr>";
foreach $workload (sort (keys %workloads)) {
    print HTML "<tr><td>$workload</td>";
    foreach $dataset (sort {$a cmp $b}(keys %datasets)) {
	if ($workloadcnt{$workload, $dataset}) {
	    printf HTML ("<td>%d</td>", $cpu{$workload, $dataset}
		/ $workloadcnt{$workload, $dataset});
        } else {
             printf HTML ("<td></td>");
        }
    }
    print HTML "</tr>";
    foreach $flowop (keys %wkl_flowops) {
        next if ("$wkl_workload{$flowop}" ne "$workload");
        print HTML "<tr><td><i>__$wkl_flowops{$flowop}</td>";
        foreach $dataset (sort {$a cmp $b}(keys %datasets)) {
	    if ($flowopcnt{$flowop, $dataset}) {
	        printf HTML ("<td>%d</td>\n", $flow_cpu{$flowop, 
		    $dataset} / $flowopcnt{$flowop, $dataset});
            } else {
                 printf HTML ("<td></td>");
            }
        }
        print HTML "</i></tr>";
    }
}
print HTML "</table>";

end_html();
